package Client.GUI;

import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

public class FrameCharacterSelection extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameCharacterSelection.class.getName());

    GraphicsDevice gd;
    
    private static final String IMAGE_PATH = "/assets/";
    private Image background;
    
    public void loadImage() {
        try {
            
            background = ImageIO.read(getClass().getResource(IMAGE_PATH + "BlackManta.png"));
            background = background.getScaledInstance(260, 200, Image.SCALE_SMOOTH);

        } catch (IOException e) {
            System.out.println("No se pudo cargar");
        }
    }
    
    public void init() {
        
        gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();

        try {
            gd.setFullScreenWindow(this);
        } catch (Exception e) {
            System.out.println("Error cargando pantalla " + e.getMessage());
        }
        
    }
    
    /**
     * Creates new form FrameCharacterSelection
     */
    public FrameCharacterSelection() {
        initComponents();
        init();
        loadImage();
        setButtonIcons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        pnlBackground = new javax.swing.JPanel();
        btnCharacterThree = new javax.swing.JButton();
        btnCharacterOne = new javax.swing.JButton();
        btnCharacterTwo = new javax.swing.JButton();
        btnCharacterFour = new javax.swing.JButton();
        btnCharacterFive = new javax.swing.JButton();
        btnCharacterSeven = new javax.swing.JButton();
        btnCharacterSix = new javax.swing.JButton();
        btnCharacterEight = new javax.swing.JButton();
        btnCharacterNine = new javax.swing.JButton();
        btnCharacterTen = new javax.swing.JButton();
        btnCharacterEleven = new javax.swing.JButton();
        btnCharacterTwelve = new javax.swing.JButton();
        btnCharacterThirteen = new javax.swing.JButton();
        btnCharacterFourteen = new javax.swing.JButton();
        btnCharacterFifteen = new javax.swing.JButton();
        btnCharacterSixteen = new javax.swing.JButton();
        btnCharacterSeventeen = new javax.swing.JButton();
        btnCharacterEighteen = new javax.swing.JButton();

        jButton4.setText("jButton1");
        jButton4.setMaximumSize(null);
        jButton4.setMinimumSize(new java.awt.Dimension(260, 200));
        jButton4.setPreferredSize(new java.awt.Dimension(260, 200));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlBackground.setBackground(new java.awt.Color(14, 51, 134));

        btnCharacterThree.setMinimumSize(new java.awt.Dimension(260, 200));
        btnCharacterThree.setPreferredSize(new java.awt.Dimension(260, 200));

        btnCharacterOne.setContentAreaFilled(false);
        btnCharacterOne.setMinimumSize(new java.awt.Dimension(260, 200));
        btnCharacterOne.setPreferredSize(new java.awt.Dimension(260, 200));

        btnCharacterTwo.setMinimumSize(new java.awt.Dimension(260, 200));
        btnCharacterTwo.setPreferredSize(new java.awt.Dimension(260, 200));
        btnCharacterTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCharacterTwoActionPerformed(evt);
            }
        });

        btnCharacterFour.setMinimumSize(new java.awt.Dimension(260, 200));
        btnCharacterFour.setPreferredSize(new java.awt.Dimension(260, 200));

        btnCharacterFive.setMinimumSize(new java.awt.Dimension(260, 200));
        btnCharacterFive.setPreferredSize(new java.awt.Dimension(260, 200));

        btnCharacterSeven.setMinimumSize(new java.awt.Dimension(260, 200));
        btnCharacterSeven.setPreferredSize(new java.awt.Dimension(260, 200));

        btnCharacterSix.setMinimumSize(new java.awt.Dimension(260, 200));
        btnCharacterSix.setPreferredSize(new java.awt.Dimension(260, 200));

        btnCharacterEight.setMinimumSize(new java.awt.Dimension(260, 200));
        btnCharacterEight.setPreferredSize(new java.awt.Dimension(260, 200));

        btnCharacterNine.setMinimumSize(new java.awt.Dimension(260, 200));
        btnCharacterNine.setPreferredSize(new java.awt.Dimension(260, 200));

        btnCharacterTen.setMinimumSize(new java.awt.Dimension(260, 200));
        btnCharacterTen.setPreferredSize(new java.awt.Dimension(260, 200));

        btnCharacterEleven.setMinimumSize(new java.awt.Dimension(260, 200));
        btnCharacterEleven.setPreferredSize(new java.awt.Dimension(260, 200));

        btnCharacterTwelve.setMinimumSize(new java.awt.Dimension(260, 200));
        btnCharacterTwelve.setPreferredSize(new java.awt.Dimension(260, 200));

        btnCharacterThirteen.setMinimumSize(new java.awt.Dimension(260, 200));
        btnCharacterThirteen.setPreferredSize(new java.awt.Dimension(260, 200));

        btnCharacterFourteen.setMinimumSize(new java.awt.Dimension(260, 200));
        btnCharacterFourteen.setPreferredSize(new java.awt.Dimension(260, 200));

        btnCharacterFifteen.setMinimumSize(new java.awt.Dimension(260, 200));
        btnCharacterFifteen.setPreferredSize(new java.awt.Dimension(260, 200));

        btnCharacterSixteen.setMinimumSize(new java.awt.Dimension(260, 200));
        btnCharacterSixteen.setPreferredSize(new java.awt.Dimension(260, 200));

        btnCharacterSeventeen.setMinimumSize(new java.awt.Dimension(260, 200));
        btnCharacterSeventeen.setPreferredSize(new java.awt.Dimension(260, 200));

        btnCharacterEighteen.setMinimumSize(new java.awt.Dimension(260, 200));
        btnCharacterEighteen.setPreferredSize(new java.awt.Dimension(260, 200));

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(btnCharacterEight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnCharacterNine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCharacterTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCharacterEleven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCharacterTwelve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCharacterThirteen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCharacterFourteen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(btnCharacterOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnCharacterTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCharacterThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCharacterFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCharacterFive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCharacterSix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCharacterSeven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(btnCharacterFifteen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCharacterSixteen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCharacterSeventeen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCharacterEighteen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCharacterThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCharacterOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCharacterTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCharacterFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCharacterFive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCharacterSeven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCharacterSix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCharacterTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCharacterEight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCharacterNine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCharacterEleven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCharacterTwelve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCharacterFourteen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCharacterThirteen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCharacterSixteen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCharacterFifteen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCharacterSeventeen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCharacterEighteen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(329, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCharacterTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCharacterTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCharacterTwoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameCharacterSelection().setVisible(true));
        
    }

    private void setButtonIcons() {
        ImageIcon icon = new ImageIcon(background);
        btnCharacterOne.setIcon(icon);
        btnCharacterTwo.setIcon(icon);
        btnCharacterThree.setIcon(icon);
        btnCharacterFour.setIcon(icon);
        btnCharacterFive.setIcon(icon);
        btnCharacterSix.setIcon(icon);
        btnCharacterSeven.setIcon(icon);
        btnCharacterEight.setIcon(icon);
        btnCharacterNine.setIcon(icon);
        btnCharacterTen.setIcon(icon);
        btnCharacterEleven.setIcon(icon);
        btnCharacterTwelve.setIcon(icon);
        btnCharacterThirteen.setIcon(icon);
        btnCharacterFourteen.setIcon(icon);
        btnCharacterFifteen.setIcon(icon);
        btnCharacterSixteen.setIcon(icon);
        btnCharacterSeventeen.setIcon(icon);
        btnCharacterEighteen.setIcon(icon);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCharacterEight;
    private javax.swing.JButton btnCharacterEighteen;
    private javax.swing.JButton btnCharacterEleven;
    private javax.swing.JButton btnCharacterFifteen;
    private javax.swing.JButton btnCharacterFive;
    private javax.swing.JButton btnCharacterFour;
    private javax.swing.JButton btnCharacterFourteen;
    private javax.swing.JButton btnCharacterNine;
    private javax.swing.JButton btnCharacterOne;
    private javax.swing.JButton btnCharacterSeven;
    private javax.swing.JButton btnCharacterSeventeen;
    private javax.swing.JButton btnCharacterSix;
    private javax.swing.JButton btnCharacterSixteen;
    private javax.swing.JButton btnCharacterTen;
    private javax.swing.JButton btnCharacterThirteen;
    private javax.swing.JButton btnCharacterThree;
    private javax.swing.JButton btnCharacterTwelve;
    private javax.swing.JButton btnCharacterTwo;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel pnlBackground;
    // End of variables declaration//GEN-END:variables
}
